services:
  - type: web
    name: visionlearn-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.0-flash
      - key: HF_API_KEY
        sync: false
      - key: HF_MODEL
        value: mistralai/Mistral-7B-Instruct-v0.3
      - key: DEBUG
        value: false
